#!/bin/bash

arg_engine="default"
sentence=
context=

if [ "$#" -gt "2" ]; then
	arg_engine="$1"
	sentence="$2"
	context="$3"
else
	sentence="$1"
	context="$2"
fi

# Import environment

__home=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
source $__home/scripts/env.sh $arg_engine

export LC_ALL=C
echo "$sentence" | $moses_home/bin/moses -f $engine_moses_dir/cfg/~moses.ini --context-string "$context" -v 0 2> /dev/null