/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class eu_modernmt_vocabulary_rocksdb_RocksDBVocabulary */

#ifndef _Included_eu_modernmt_vocabulary_rocksdb_RocksDBVocabulary
#define _Included_eu_modernmt_vocabulary_rocksdb_RocksDBVocabulary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     eu_modernmt_vocabulary_rocksdb_RocksDBVocabulary
 * Method:    instantiate
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_eu_modernmt_vocabulary_rocksdb_RocksDBVocabulary_instantiate
  (JNIEnv *, jobject, jstring);

/*
 * Class:     eu_modernmt_vocabulary_rocksdb_RocksDBVocabulary
 * Method:    lookup
 * Signature: (Ljava/lang/String;Z)I
 */
JNIEXPORT jint JNICALL Java_eu_modernmt_vocabulary_rocksdb_RocksDBVocabulary_lookup
  (JNIEnv *, jobject, jstring, jboolean);

/*
 * Class:     eu_modernmt_vocabulary_rocksdb_RocksDBVocabulary
 * Method:    lookupLine
 * Signature: ([Ljava/lang/String;Z)[I
 */
JNIEXPORT jintArray JNICALL Java_eu_modernmt_vocabulary_rocksdb_RocksDBVocabulary_lookupLine
  (JNIEnv *, jobject, jobjectArray, jboolean);

/*
 * Class:     eu_modernmt_vocabulary_rocksdb_RocksDBVocabulary
 * Method:    lookupLines
 * Signature: ([[Ljava/lang/String;[[IZ)V
 */
JNIEXPORT void JNICALL Java_eu_modernmt_vocabulary_rocksdb_RocksDBVocabulary_lookupLines
  (JNIEnv *, jobject, jobjectArray, jobjectArray, jboolean);

/*
 * Class:     eu_modernmt_vocabulary_rocksdb_RocksDBVocabulary
 * Method:    reverseLookup
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_eu_modernmt_vocabulary_rocksdb_RocksDBVocabulary_reverseLookup
  (JNIEnv *, jobject, jint);

/*
 * Class:     eu_modernmt_vocabulary_rocksdb_RocksDBVocabulary
 * Method:    reverseLookupLine
 * Signature: ([I)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_eu_modernmt_vocabulary_rocksdb_RocksDBVocabulary_reverseLookupLine
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     eu_modernmt_vocabulary_rocksdb_RocksDBVocabulary
 * Method:    reverseLookupLines
 * Signature: ([[I[[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_eu_modernmt_vocabulary_rocksdb_RocksDBVocabulary_reverseLookupLines
  (JNIEnv *, jobject, jobjectArray, jobjectArray);

/*
 * Class:     eu_modernmt_vocabulary_rocksdb_RocksDBVocabulary
 * Method:    dispose
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_eu_modernmt_vocabulary_rocksdb_RocksDBVocabulary_dispose
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
