/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class eu_modernmt_aligner_fastalign_FastAlign */

#ifndef _Included_eu_modernmt_aligner_fastalign_FastAlign
#define _Included_eu_modernmt_aligner_fastalign_FastAlign
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     eu_modernmt_aligner_fastalign_FastAlign
 * Method:    init
 * Signature: (Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_eu_modernmt_aligner_fastalign_FastAlign_init
  (JNIEnv *, jobject, jstring, jboolean);

/*
 * Class:     eu_modernmt_aligner_fastalign_FastAlign
 * Method:    align
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_eu_modernmt_aligner_fastalign_FastAlign_align
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     eu_modernmt_aligner_fastalign_FastAlign
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_eu_modernmt_aligner_fastalign_FastAlign_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
