/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class eu_modernmt_aligner_fastalign_FastAlign */

#ifndef _Included_eu_modernmt_aligner_fastalign_FastAlign
#define _Included_eu_modernmt_aligner_fastalign_FastAlign
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     eu_modernmt_aligner_fastalign_FastAlign
 * Method:    instantiate
 * Signature: (Ljava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_eu_modernmt_aligner_fastalign_FastAlign_instantiate
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     eu_modernmt_aligner_fastalign_FastAlign
 * Method:    alignPair
 * Signature: (Ljava/lang/String;Ljava/lang/String;)[[I
 */
JNIEXPORT jobjectArray JNICALL Java_eu_modernmt_aligner_fastalign_FastAlign_alignPair
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     eu_modernmt_aligner_fastalign_FastAlign
 * Method:    alignPairs
 * Signature: ([Ljava/lang/String;[Ljava/lang/String;)[[[I
 */
JNIEXPORT jobjectArray JNICALL Java_eu_modernmt_aligner_fastalign_FastAlign_alignPairs
  (JNIEnv *, jobject, jobjectArray, jobjectArray);

/*
 * Class:     eu_modernmt_aligner_fastalign_FastAlign
 * Method:    dispose
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_eu_modernmt_aligner_fastalign_FastAlign_dispose
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
