/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class eu_modernmt_aligner_fastalign_FastAlign */

#ifndef _Included_eu_modernmt_aligner_fastalign_FastAlign
#define _Included_eu_modernmt_aligner_fastalign_FastAlign
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     eu_modernmt_aligner_fastalign_FastAlign
 * Method:    instantiate
 * Signature: (Ljava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_eu_modernmt_aligner_fastalign_FastAlign_instantiate
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     eu_modernmt_aligner_fastalign_FastAlign
 * Method:    align
 * Signature: ([I[II)[I
 */
JNIEXPORT jintArray JNICALL Java_eu_modernmt_aligner_fastalign_FastAlign_align___3I_3II
  (JNIEnv *, jobject, jintArray, jintArray, jint);

/*
 * Class:     eu_modernmt_aligner_fastalign_FastAlign
 * Method:    align
 * Signature: ([[I[[I[[II)V
 */
JNIEXPORT void JNICALL Java_eu_modernmt_aligner_fastalign_FastAlign_align___3_3I_3_3I_3_3II
  (JNIEnv *, jobject, jobjectArray, jobjectArray, jobjectArray, jint);

/*
 * Class:     eu_modernmt_aligner_fastalign_FastAlign
 * Method:    dispose
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_eu_modernmt_aligner_fastalign_FastAlign_dispose
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
