/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class eu_modernmt_vocabulary_VocabularyBuilder */

#ifndef _Included_eu_modernmt_vocabulary_VocabularyBuilder
#define _Included_eu_modernmt_vocabulary_VocabularyBuilder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     eu_modernmt_vocabulary_VocabularyBuilder
 * Method:    flush
 * Signature: ([Ljava/lang/String;[IILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_eu_modernmt_vocabulary_VocabularyBuilder_flush
  (JNIEnv *, jobject, jobjectArray, jintArray, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
