#!/usr/bin/env python
import argparse

import logging
import os

import sys

sys.path.insert(0, os.path.abspath(os.path.join(__file__, os.pardir, os.pardir)))

from cli.mmt.engine import Engine

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Tune MMT engine')
    parser.add_argument('path', default=None, help='the path to the training corpora')
    parser.add_argument('-e', '--engine', dest='engine', help='the engine name, \'default\' will be used if absent',
                        default='default')

    # Parse args
    args = parser.parse_args()

    logging.basicConfig(format='%(asctime)-15s [%(levelname)s] - %(message)s', level=logging.INFO)
    engine = Engine.load(args.engine)
    engine.tune(args.path, engine.get_tempdir('nmt_tuning'))
