#!/usr/bin/python

# Translate script for debugging directly on the server
# Provide translation, nbest and context scores

# Execute without parameters so discover syntax

import sys
import requests
import json
import string
import pprint

argv = sys.argv[1:]

if len(sys.argv) < 2:
    sys.stderr.write('\nUsage: '+sys.argv[0]+' "Hello World" ["This is an optional context"] [# of translation options] [API port]\n')
    sys.exit(1)


## Setting parameters
q = argv[0]

context = ''
if len(sys.argv)>2 :
  context = argv[1]

nbest = 10
if len(sys.argv)>3 :
  nbest = int(argv[2])

port = 8045
if len(sys.argv)>4 :
  port = int(argv[3])

data = {"q" : q , "context" : context , "nbest" : nbest}
r = requests.get("http://localhost:"+str(port)+"/translate?", params = data)
j = json.loads(r.text)

print("\nBest Translation:")
print(j["translation"])

print("\nTop "+str(nbest)+" results:")
for index in range(nbest):
   print(j["nbest"][index]["translation"])

if (len(sys.argv)>2) and (len(argv[1])>0) :
 print("\nContext Scores:")
 print json.dumps(j["context"], indent=4, sort_keys=True)

# END
print("\n")
