#!/usr/bin/env python
import argparse
import os
import sys

sys.path.insert(0, os.path.abspath(os.path.join(__file__, os.pardir, os.pardir)))

from cli.build import git_checkout, build_all


def main_update(argv):
    # Set unbuffered stdout
    unbuffered = os.fdopen(sys.stdout.fileno(), 'w', 0)
    sys.stdout = unbuffered

    parser = argparse.ArgumentParser(description='Update from git and compile complete MMT system from sources (for developers)')
    parser.prog = 'update'
    parser.add_argument('branch', nargs='?', default=None, help='git branch to check out prior to update')

    args = parser.parse_args(argv)

    if args.branch:
        git_checkout(args.branch)
    build_all()


if __name__ == '__main__':
    main_update(sys.argv[1:])
