#!/usr/bin/python
import os
import sys

sys.path.insert(0, os.path.abspath(os.path.join(__file__, os.pardir, os.pardir)))

from cli.mmt.processing import XMLEncoder

__author__ = 'Davide Caroselli'

if __name__ == '__main__':
    encoder = XMLEncoder()

    for line in sys.stdin:
        line = line.rstrip('\r\n') + '\n'
        encoded = encoder.encode_string(line.decode('utf-8'))
        sys.stdout.write(encoded.encode('utf-8'))
